name    'puppet-module-apachefixes'
version '0.2.0'
source 'git://github.com/emahags/puppet-module-apachefixes.git'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'Wrapper module for apache'
description 'Wrapper module for apache'
project_page 'https://github.com/emahags/puppet-module-apachefixes'

dependency 'puppetlabs/apache', '>= 0.1.2'
